[package]
edition = "2021"
name    = "opa-tp"
version = "0.1.0"

[lib]
name = "opa_tp"
path = "src/lib.rs"

[[bin]]
name = "opa-tp"
path = "src/main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.61"
bytes = "1.3.0"
chronicle-telemetry = { path = "../chronicle-telemetry" }
chrono = "0.4.19"
clap = { version = "3.2.1", features = ["derive", "env"] }
k256 = { version = "0.11.3", features = [
  "default",
  "arithmetic",
  "ecdsa",
  "pkcs8",
  "sha256",
  "std",
  "pem",
] }
opa-tp-protocol = { path = "../opa-tp-protocol" }
prost = "0.11.3"
proto = { path = "../sawtooth-protocol" }
sawtooth-sdk = "0.5.2"
serde_json = "1.0.79"
thiserror = "1.0.36"
tokio = { version = "1.17.0", features = ["time", "macros", "rt-multi-thread"] }
tracing = "0.1.37"
url = "2.3.1"

[dev-dependencies]
chronicle-telemetry = { path = "../chronicle-telemetry" }
insta               = { version = "1.14.0", features = ["redactions", "toml", "yaml"] }
protobuf            = "2.27.1"
rand                = { version = "0.8.5", features = ["getrandom"] }
rand_core           = "0.6.3"
tempfile = "3.3.0"
