# An example Trunk.toml with all possible fields along with their defaults.

[build]
# The index HTML file to drive the bundling process.
target = "index.html"
# Build in release mode.
release = false
# The output dir for all final assets.
dist = "../web-target"
# The public URL from which assets are to be served.
public_url = "/"

[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = []
# Paths to ignore.
ignore = []

[serve]
# The address to serve on.
addr = "0.0.0.0"
# The port to serve on.
port = 8080
# Open a browser tab once the initial build is complete.
open = false
# Disable auto-reload of the web app.
no_autoreload = false

[clean]
# The output dir for all final assets.
dist = "../web-target"
# Optionally perform a cargo clean.
cargo = false

[tools]
# Default dart-sass version to download.
sass = "1.37.5"
# Default wasm-bindgen version to download.
wasm_bindgen = "0.2.74"
# Default wasm-opt version to download.
wasm_opt = "version_102"

## proxy
# Proxies are optional, and default to `None`.
# Proxies are only run as part of the `trunk serve` command.
[[proxy]]
backend = "http://127.0.0.1:9982/events"

## hooks
# Hooks are optional, and default to `None`.
# Hooks are executed as part of Trunk's main build pipeline, no matter how it is run.