---
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        exclude: "charts/.*"
        args:
          - --allow-multiple-documents
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
        exclude: "api/src/lib.rs"
      - id: end-of-file-fixer
        exclude: "docs/diagrams/out/.*"
      - id: mixed-line-ending
        exclude: "docs/diagrams/out/.*"
      - id: no-commit-to-branch
        args:
          - --pattern
          - '^(?!((fix|feature|refactor)\/[a-zA-Z0-9\-]+)$).*'
      - id: trailing-whitespace
        exclude: "docs/docs/diagrams/out/.*"
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.18
    hooks:
      - id: helmlint
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
        exclude: "^(.*.png|.*.jpg|.*.jpeg|charts/chronicle/charts/.*)"
      - id: shellcheck
        args:
          - -a
          - -x
          - -e
          - SC1072,SC1073
      - id: script-must-have-extension
      - id: script-must-not-have-extension
      - id: shfmt
        args:
          - -l
          - -i
          - "2"
          - -ci
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        args:
          - --config
          - .mdlrc
        #Autogenerated, big links
        exclude: "^(CHANGELOG.md|charts/.*)"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.34.0
    hooks:
      - id: eslint
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: forbid-tabs
        exclude: "^(.*/?Makefile|.*.mk|.*.go|docs/diagrams/out/.*)$"
  - repo: https://github.com/doublify/pre-commit-go
    rev: 208a4aaa7f86b44e961eaaea526743b920e187a0
    hooks:
      - id: fmt
      - id: vet
      - id: fix
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint
        exclude: ".*/templates/.*|charts/.*"
        args:
          - -c
          - .yamllint-config.yaml
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.1.1
    hooks:
      - id: docker-compose-check
        files: docker-compose.*y[a]{0,1}ml$
      - id: docker-compose-check
        files: "^docker/.*yaml$"
  - repo: https://gitlab.com/daverona/pre-commit/cpp
    rev: 0.8.0
    hooks:
      - id: docker-cppcheck
        args:
          - --force
