[workspace]

members = [
  "common",
  "api",
  "chronicle",
  "chronicle-domain-lint",
  "chronicle-domain-test",
  "chronicle-domain",
  "sawtooth-protocol",
  "sawtooth-tp",
  "telemetry",
]

[profile.release]
codegen-units = 1
lto           = true
opt-level     = 'z'
