[workspace]

members = [
  "common",
  "api",
  "bootstrap",
  "cli",
  "sawtooth_protocol",
  "sawtooth_tp",
  "meta-chronicle/impl",
  "meta-chronicle/macro",
]


[profile.release]
codegen-units = 1
lto           = true
opt-level     = 'z'

[profile.release.build-override]
codegen-units = 1
opt-level     = 'z'
