[workspace]

members = [
  "common",
  "api",
  "chronicle",
  "chronicle-example",
  "chronicle-untyped",
  "sawtooth_protocol",
  "sawtooth_tp",
  "telemetry",
]


[profile.release]
codegen-units = 1
lto           = true
opt-level     = 'z'

[profile.release.build-override]
codegen-units = 1
opt-level     = 'z'
