[workspace]

members = ["common", "api", "cli", "sawtooth_protocol", "sawtooth_tp"]


[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[profile.release.build-override]
opt-level = 'z'
codegen-units = 1
