---
site_name: Chronicle
site_author: Chronicle Team
docs_dir: docs
theme:
  name: material
  palette:
    scheme: Chronicle
  logo: assets/logos/logo.png
  favicon: assets/logos/favicon.png
  features:
    - content.code.copy
copyright: Copyright &copy; 2023 The Chronicle Authors | Documentation distributed under CC BY 4.0
strict: false
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - docs/includes/glosary.md
  - pymdownx.superfences
plugins:
  - search
  - build_plantuml:
      theme_enabled: false
      render: "server"
      server: "https://www.plantuml.com/plantuml"
      disable_ssl_certificate_validation: false
      output_format: "svg"
      diagram_root: "docs/diagrams"
      output_folder: "out"
      input_folder: "src"
      input_extensions: ""
nav:
  - Overview: index.md
  - Architecture: chronicle_architecture.md
  - Vocabulary: chronicle_vocabulary.md
  - Development:
      - Provenance concepts: provenance_concepts.md
      - Modeling a provenance domain: domain_modeling.md
      - Recording provenance: recording_provenance.md
      - Querying provenance: querying_provenance.md
      - Untyped Chronicle: untyped_chronicle.md
      - Namespaces: namespaces.md
  - Testing:
      - Building your domain: building.md
      - Health Checks and Testing: health-checks-and-testing.md
      - Helm Testing: helm-testing.md
  - Installing:
      - Rancher by SUSE Cookbook: rancher.md
      - Configuring Helm:
          - Security settings: helm-jwks-opa.md
          - Security scenarios: helm-scenarios.md
          - Misc Options: helm-options.md
          - External PostgreSQL: external-postgres.md
      - Configuring Sawtooth:
          - Resetting Chronicle: resetting.md
          - Connecting to Chronicle: connecting.md
  - Operating:
      - CLI: cli.md
      - Configuration options: config.md
      - Establishing identity: auth.md
      - Access control policy: opa.md
      - Authorization checking: oidc-opa-flow.md
      - Importing data: importing.md
  - Upgrading: upgrading.md
  - Legacy Links:
      - Docs: chronicle.md
      - Cookbook: cookbooks/chronicle/rancher.md
