site_name: chronicle
site_author: BTP
theme:
  name: material
  palette:
    scheme: default
copyright: Copyright &copy; 2022-23 Blockchain Technology Partners
strict: false
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - docs/includes/glosary.md
  - pymdownx.superfences
plugins:
  - search
  - build_plantuml:
      theme_enabled: false
      render: "server"
      server: "https://www.plantuml.com/plantuml"
      disable_ssl_certificate_validation: false
      output_format: "svg"
      diagram_root: "docs/diagrams"
      output_folder: "out"
      input_folder: "src"
      input_extensions: ""
nav:
  - Overview: index.md
  - Architecture: chronicle_architecture.md
  - Installing:
      - Building for your domain: building.md
      - Installing with Sextant: sextant.md
  - Development:
      - Provenance concepts: provenance_concepts.md
      - Modeling a provenance domain: domain_modeling.md
      - Recording provenance: recording_provenance.md
      - Querying provenance: querying_provenance.md
      - Untyped Chronicle: untyped_chronicle.md
  - Upgrading: upgrading.md
  - Operating:
      - CLI: cli.md
      - Configuration options: config.md
      - Authentication and authorization: authz.md
