services:
  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.1
    depends_on:
      - validator
    entrypoint: settings-tp -v --connect tcp://validator:4004
    volumes:
      - /dev/urandom:/dev/random
      - /dev/urandom:/dev/urandom

  validator:
    image: hyperledger/sawtooth-validator:1.1
    expose:
      - 4004
      - 8800
      - 5050
    ports:
      - "4004:4004"
      - "8800:8800"
      - "5050:5050"
    entrypoint: "bash -c \"\
      sawadm keygen && \
      sawtooth keygen && \
      sawset genesis -k /etc/sawtooth/keys/validator.priv \
      -o config-genesis.batch && \
      sawset proposal create -k /etc/sawtooth/keys/validator.priv \
      sawtooth.consensus.min_wait_time=0 \
      sawtooth.consensus.max_wait_time=0 \
      -o consensus-settings.batch && \
      sawadm genesis config-genesis.batch consensus-settings.batch && \
      sawtooth-validator -v \
      --scheduler parallel \
      --endpoint tcp://validator:8800 \
      --bind component:tcp://eth0:4004 \
      --bind consensus:tcp://eth0:5050 \
      --bind network:tcp://eth0:8800 \
      \""
    volumes:
      - /dev/urandom:/dev/random
      - /dev/urandom:/dev/urandom

  devmode-engine:
    image: hyperledger/sawtooth-devmode-engine-rust:1.1
    depends_on:
      - validator
    entrypoint: devmode-engine-rust -C tcp://validator:5050
    volumes:
      - /dev/urandom:/dev/random
      - /dev/urandom:/dev/urandom

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.1
    expose:
      - 8008
    ports:
      - "8008:8008"
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api  --connect tcp://validator:4004 --bind rest-api:8008
    volumes:
      - /dev/urandom:/dev/random
      - /dev/urandom:/dev/urandom

  chronicle-sawtooth-tp:
    image: "${REGISTRY}chronicle-sawtooth-tp:${ISOLATION_ID}"
    command: "chronicle_sawtooth_tp tcp://validator:4004"
    depends_on:
      - validator
    volumes:
      - /dev/urandom:/dev/random
      - /dev/urandom:/dev/urandom

  chronicle-sawtooth-api:
    image: "${REGISTRY}chronicle:${ISOLATION_ID}"
    command: "chronicle --ui"
    depends_on:
      - validator
    volumes:
      - /dev/urandom:/dev/random
      - /dev/urandom:/dev/urandom
