[package]
name = "chronicle-domain-lint"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.2.1"
jsonschema = "0.16"
serde_json = "1.0.81"
serde_yaml = "0.9.14"
chronicle = { path = "../chronicle" }
