[package]
edition = "2021"
name    = "opactl"
version = "0.7.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-sawtooth-sdk  = { path = "../async-sawtooth-sdk" }
async-trait         = { workspace = true }
chronicle-telemetry = { path = "../chronicle-telemetry" }
clap                = { version = "4.1.1", features = ["env"] }
const_format        = { workspace = true }
futures             = { workspace = true }
k256                = { workspace = true }
lazy_static         = { workspace = true }
opa-tp-protocol     = { path = "../opa-tp-protocol" }
pin-project         = { workspace = true }
rand                = { workspace = true }
rand_core           = { workspace = true }
sawtooth-sdk        = { workspace = true }
serde               = { workspace = true }
serde_derive        = { workspace = true }
serde_json          = { workspace = true }
thiserror           = { workspace = true }
tokio               = { workspace = true }
tokio-stream        = { workspace = true }
tracing             = { workspace = true }
url                 = { workspace = true }
user-error          = { workspace = true }

[dev-dependencies]
hex        = { workspace = true }
insta      = { workspace = true, features = ["yaml"] }
opa-tp     = { path = "../opa-tp" }
prost      = { workspace = true }
protobuf   = { workspace = true }
serde_json = { workspace = true }
tempfile   = { workspace = true }
