[package]
edition = "2021"
name    = "opactl"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = { version = "4.1.1", features = ["env"] }
k256 = { version = "0.11.3", features = [
  "default",
  "arithmetic",
  "ecdsa",
  "pkcs8",
  "sha256",
  "std",
  "pem",
] }
opa-tp-protocol = { path = "../opa-tp-protocol" }
url = "2.3.1"
