[[bin]]
name = "chronicle_sawtooth_tp"
path = "src/main.rs"

[lib]
name = "chronicle_sawtooth_tp"
path = "src/lib.rs"

[package]
build   = "build.rs"
edition = "2021"
name    = "sawtooth_tp"
version = "0.7.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-sawtooth-sdk   = { path = "../async-sawtooth-sdk" }
async-trait          = { workspace = true }
backoff              = { workspace = true }
bytes                = { workspace = true }
chronicle-protocol   = { path = "../chronicle-protocol" }
chronicle-telemetry  = { path = "../chronicle-telemetry" }
clap                 = { workspace = true }
clap_generate        = { workspace = true }
common               = { path = "../common" }
const_format         = { workspace = true }
crossbeam            = { workspace = true }
custom_error         = { workspace = true }
derivative           = { workspace = true }
futures              = { workspace = true }
glob                 = { workspace = true }
hex                  = { workspace = true }
lazy_static          = { workspace = true }
opa-tp-protocol      = { path = "../opa-tp-protocol" }
openssl              = { workspace = true }
opentelemetry        = { workspace = true }
opentelemetry-jaeger = { workspace = true }
prost                = "0.10.0"
rand                 = { workspace = true }
rand_core            = { workspace = true }
sawtooth-sdk         = { workspace = true }
serde                = { workspace = true }
serde_derive         = { workspace = true }
serde_json           = { workspace = true }
tokio                = { workspace = true }
tracing              = { workspace = true }
url                  = { workspace = true }
uuid                 = { workspace = true }
zmq                  = { workspace = true }

[build-dependencies]
glob        = { workspace = true }
prost-build = { workspace = true }

[dev-dependencies]
insta    = { workspace = true, features = ["yaml"] }
protobuf = { workspace = true }
tempfile = { workspace = true }

[features]
default          = ["vendored-zmq", "vendored-openssl"]
vendored-openssl = ['openssl/vendored']
vendored-zmq     = ['zmq/vendored']
