[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.5", features = ["yaml"] }
question = "0.2.2"
api = {path = "../api"}
user-error = "1.2.8"
url = { version = "2.2.2", features = ["serde"] }
serde = "1.0.130"
toml = "0.5.8"
custom_error = "1.9.2"
serde_derive = "1.0.130"
rand = { version = "0.8.4", features = ["getrandom"] }
pkcs8 = { version = "0.7.6", features = ["alloc", "std"] }
k256 = { version = "0.9.6", features = ["std","pem","pkcs8"] }
hex = "0.4.3"
rand_core = "0.6.3"
shellexpand = "2.1.0"
tracing = "0.1.29"
tracing-subscriber = "0.2.25"
proto = {path="../proto"}
common = {path="../common"}
uuid = "0.8.2"
colored_json = "2.1.0"

[features]
# Use an in memory stub ledger
inmem = []
