[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.5", features = ["yaml"] }
question = "0.2.2"
toml-config = "0.4.0"
api = {path = "../api"}
user-error = "1.2.8"
url = "2.2.2"
rand = "0.8.4"

