[package]
build   = "build.rs"
edition = "2021"
name    = "chronicle-example"
version = "0.6.0"

[[bin]]
name = "chronicle-example"
path = "src/test.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chronicle = { path = "../chronicle" }
chronicle-telemetry = { path = "../chronicle-telemetry" }
tracing = "0.1.34"
tracing-log = "0.1.3"
uuid = "1.0.0"

[build-dependencies]
chronicle = { path = "../chronicle" }

[features]
strict = []
devmode = ["anonymous-api", "inmem"]
# Allow unauthenticated API access
anonymous-api = ["chronicle/anonymous-api"]
# Use an in-memory stub ledger
inmem = ["chronicle/inmem"]

[dev-dependencies]
futures = "0.3"
insta    = { version = "1.14.0", features = ["json", "redactions", "toml"] }
tempfile = "3.3.0"
