[package]
edition = "2021"
name = "gq-ws"
version = "0.7.5"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
http = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }
tungstenite = { workspace = true }
