[[bin]]
name = "chronicle_sawtooth_tp"
path = "src/main.rs"

[package]
edition = "2021"
name    = "sawtooth_tp"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.53"
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
bytes = "1.1.0"
clap = "3.2.1"
clap_generate = "3.0.3"
common = { path = "../common" }
crossbeam = "0.8.1"
custom_error = "1.9.2"
derivative = "2.2.0"
futures = "0.3.21"
glob = "0.3.0"
hex = "0.4.3"
lazy_static = "1.4.0"
openssl = "0.10.38"
opentelemetry = { version = "0.17.0", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.16.0", features = [
  "rt-tokio",
  "reqwest_collector_client",
  "collector_client",
] }
prost = "0.10.0"
proto = { path = "../sawtooth-protocol" }
rand = { version = "0.8.5", features = ["getrandom"] }
rand_core = "0.6.3"
sawtooth-sdk = "0.5.2"
serde = "1.0.136"
serde_cbor = "0.11.2"
serde_derive = "1.0.136"
telemetry = { path = "../telemetry" }
tokio = { version = "1.17.0", features = ["time", "macros", "rt-multi-thread"] }
tracing = "0.1.32"
url = "2.2.2"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
zmq = "0.9.2"

[build-dependencies]
glob        = "0.3.0"
prost-build = "0.10.0"

[dev-dependencies]
protobuf = "2.27.1"

[features]
default          = ["vendored-zmq", "vendored-openssl"]
vendored-openssl = ['openssl/vendored']
vendored-zmq     = ['zmq/vendored']
