[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iref = "2.0.3"
iref-enum = "1.2.0"
static-iref = "1.0.0"
serde = "1.0.130"
serde_derive = "1.0.130"
uuid = { version = "0.8.2", features = ["serde"] }
rand = { version = "0.8.4", features = ["getrandom"] }
pkcs8 = { version = "0.7.6", features = ["alloc", "std"] }
k256 = { version = "0.9.6", features = ["std","pem","pkcs8"] }
hex = "0.4.3"
rand_core = "0.6.3"
custom_error = "1.9.2"
glob = "0.3.0"
json = "0.12.4"
chrono = { version = "0.4.19", features = ["serde"] }
multimap = "0.8.3"
lazy_static = "1.4.0"
json-ld = "0.4.0"
async-std = "1.10.0"

