[package]
build   = "build.rs"
edition = "2021"
name    = "proto"
version = "0.6.0"

[lib]
name = "sawtooth_protocol"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait.workspace  = true
backoff.workspace      = true
bytes.workspace        = true
common                 = { path = "../common" }
custom_error.workspace = true
derivative.workspace   = true
futures.workspace      = true
glob.workspace         = true
hex.workspace          = true
lazy_static.workspace  = true
openssl.workspace      = true
prost                  = "0.10.0"
prost-types.workspace  = true
rand.workspace         = true
rand_core.workspace    = true
sawtooth-sdk.workspace = true
serde.workspace        = true
serde_cbor.workspace   = true
serde_derive.workspace = true
tokio.workspace        = true
tracing.workspace      = true
url.workspace          = true
uuid.workspace         = true
zmq.workspace          = true

[build-dependencies]
glob.workspace        = true
prost-build.workspace = true

[dev-dependencies]
protobuf.workspace = true
tempfile.workspace = true

[features]
default          = ["vendored-zmq", "vendored-openssl"]
vendored-openssl = ['openssl/vendored']
vendored-zmq     = ['zmq/vendored']
