[package]
edition = "2021"
name    = "telemetry"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opentelemetry = { version = "0.17.0", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.16.0", features = [
  "rt-tokio",
  "collector_client",
  "reqwest_collector_client",
] }
tracing = "0.1.36"
tracing-elastic-apm = "3.2.3"
tracing-log = "0.1.3"
tracing-opentelemetry = "0.17.4"
tracing-subscriber = { version = "0.3.15", features = [
  "default",
  "registry",
  "env-filter",
  "json",
] }
url = { version = "2.2.2", features = ["serde"] }
