[package]
edition = "2021"
name    = "chronicle"
version = "0.6.0"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = "0.11.4"
api = { path = "../api" }
async-graphql = "4.0.9"
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.2.1", features = ["derive", "env"] }
clap_complete = "3.1.1"
colored_json = "3.0.1"
common = { path = "../common" }
diesel = { version = "2.0.0-rc.0", features = [
  "postgres",
  "uuid",
  "chrono",
  "r2d2",
] }
dotenv = "0.15.0"
futures = "0.3.21"
genco = "0.16.1"
hex = "0.4.3"
iref = "2.1.2"
jsonschema = "0.16"
opa = "0.9.0"
open = "3.2.0"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.17.0", features = [
  "rt-tokio",
  "collector_client",
  "reqwest_collector_client",
] }
percent-encoding = "2.1.0"
pg-embed = "0.6.5"
proto = { path = "../sawtooth-protocol" }
question = "0.2.2"
rand = { version = "0.8.5", features = ["getrandom"] }
rand_core = "0.6.3"
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.81"
serde_yaml = "0.9.14"
shellexpand = "3.0.0"
chronicle-telemetry = { path = "../chronicle-telemetry" }
thiserror = "1.0.38"
tokio = { version = "1.20.3", features = ["time", "macros", "rt-multi-thread"] }
toml = "0.5.8"
tracing = "0.1.32"
tracing-log = "0.1.2"
url = { version = "2.2.2", features = ["serde"] }
user-error = "1.2.8"
uuid = "0.8.2"
valico = "3.6.0"


[features]
devmode = ["inmem"]
# Use an in-memory stub ledger
inmem  = []
strict = []

[build-dependencies]

[dev-dependencies]
assert_fs = "1.0"
insta     = { version = "1.14.0", features = ["redactions", "toml", "yaml"] }
tempfile  = "3.3.0"
