[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_error = "1.9.2"
diesel = { version = "1.4.8", features = ["postgres"] }
dotenv = "0.15.0"
iref-enum = "1.2.0"
json-ld = "0.4.0"
validator = { version = "0.14.0", features = ["derive"] }
